---
- include_tasks: get-site.yml

- name: deploy dev
  git:
    repo: "{{ site_repo }}"
    dest: "{{ dev_dest }}"
    version: "{{ dev_branch }}"
  when: commit.changed

- name: deploy staging
  git:
    repo: "{{ site_repo }}"
    dest: "{{ staging_dest }}"
    version: "{{ staging_branch }}"
  when: version.changed

- name: add script to auto update
  template:
    src: update_site.sh.j2
    dest: "{{ site_update_script_dest }}/update_site.sh"
    mode: 0755
- name: Add crontab job fetch to the site every N minutes
  cron:
    name: "update site"
    minute: "*/{{ site_update_every_n_min }}"
    job: "{{ site_update_script_dest }}/update_site.sh"
