---
# Site
site_repo: "https://github.com/kaleocheng/test-devops-site.git"

# the dest on server
site_dest: "/data/site"
site_version: "{{ site_dest }}/version"
site_update_script_dest: "/usr/local/bin"
site_update_every_n_min: 5
# Change the servername to yours
dev_servername: "dev.kaleo.run"
dev_dest: "/var/www/html/dev.kaleo.run"
## git branch for dev
dev_branch: "dev-gh-pages"

staging_servername: "staging.kaleo.run"
staging_dest: "/var/www/html/staging.kaleo.run"
staging_branch: "staging-gh-pages"

# Nginx and Git
nginx_sites:
        dev.kaleo.run:
          - listen 80
          - server_name "{{ dev_servername }}"
          - root "{{ dev_dest }}" 
          - index index.html
        staging.kaleo.run:
          - listen 80
          - server_name "{{ staging_servername }}"
          - root "{{ staging_dest }}" 
          - index index.html
          
git_packages:
  - git
